### ISSUE TITLE
Mention https://jenkins.io/artwork/ as a source of the additional Jenkins artwork

### ISSUE THREAD

**Issue by oleg-nenashev** [cdfoundation/artwork#15]
Jenkins project has its own listing of the artwork which is being used by meetups and subprojects: https://jenkins.io/artwork/ . It would be great to add a reference to this page inside the repository

P,S: just creating small tasks which could be picked by others, feel free to mark them as `hacktoberfest` ;)

**Comment by danlopez00** [comment]
added attribution in readme
