### ISSUE TITLE
Add Jenkins favicon to the repo

### ISSUE THREAD

**Issue by oleg-nenashev** [cdfoundation/artwork#16]
Currently the Jenkins projects uses a favicon which is not listed in this repo: https://raw.githubusercontent.com/jenkins-infra/jenkins.io/master/content/sites/default/files/jenkins_favicon.ico . It would be nice to add it to the official listing.

There is also an SVG monothone version on simpleicons: https://github.com/simple-icons/simple-icons/blob/develop/icons/jenkins.svg

P,S: just creating small tasks which could be picked by others, feel free to mark them as hacktoberfest ;)

**Comment by danlopez00** [comment]
https://github.com/cdfoundation/artwork/tree/master/jenkins/icon/favicon
