### ISSUE TITLE
update readme with full list of screwdriver logos when ready

### ISSUE THREAD

**Issue by danlopez00** [cdfoundation/artwork#21]
update readme with full list of screwdriver logos when ready

**Comment by tkyi** [comment]
Hi @danlopez00 , could you review this PR to add Screwdriver logos to the artwork table for me?
https://github.com/cdfoundation/artwork/pull/36

**Comment by tkyi** [comment]
thank you!

**Comment by zestyroxy** [comment]
Thank you @tkyi!
