### ISSUE TITLE
Add Shipwright Logos

### ISSUE THREAD

**Issue by adambkaplan** [cdfoundation/artwork#37]
Shipwright's logos are missing from the artwork page.

The official assets can be found on the project's community repository: https://github.com/shipwright-io/community/tree/main/assets/icons/png

**Comment by fdegir** [comment]
Thanks for highlighting this Adam. I'll work with @zestyroxy to bring the Shipwright artwork to this repo and let you know.

**Comment by zestyroxy** [comment]
The repo is there @adambkaplan. Do you mean displayed in the table in the README?

https://github.com/cdfoundation/artwork
https://github.com/cdfoundation/artwork/tree/main/shipwright/icons
